USE autorent_pro;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) DEFAULT '',
ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'ADMIN',
ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;

ALTER TABLE vehicles
ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS insurance_end DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS technical_visit_end DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS vignette_end DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS driving_license VARCHAR(80);

UPDATE users SET active=1, full_name='Administrateur', role='ADMIN' WHERE username='admin';
