USE autorent_pro;

CREATE TABLE IF NOT EXISTS maintenance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vehicle_id INT NULL,
  maintenance_date DATE,
  type VARCHAR(80) DEFAULT 'VIDANGE',
  mileage INT DEFAULT 0,
  amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(30) DEFAULT 'TERMINEE',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE expenses
ADD COLUMN IF NOT EXISTS category VARCHAR(80) DEFAULT 'AUTRE';

ALTER TABLE expenses
ADD COLUMN IF NOT EXISTS vehicle_id INT NULL,
ADD COLUMN IF NOT EXISTS expense_date DATE,
ADD COLUMN IF NOT EXISTS label VARCHAR(150),
ADD COLUMN IF NOT EXISTS amount DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS notes TEXT;
