USE autorent_pro;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'ADMIN';
ALTER TABLE users ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS active TINYINT(1) NOT NULL DEFAULT 1;
UPDATE users SET active=1, full_name='Administrateur', role='ADMIN' WHERE username='admin';
